import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import SplashScreen from "@/components/SplashScreen";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SplashScreen>
          <Header />
          <div className="pt-16 px-[28px]">{children}</div>
        </SplashScreen>
      </body>
    </html>
  );
}
